[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
]
