exec-once = kanshi &
source = ~/.config/hypr/common.conf
exec-once = $HOME/bin/zup.sh &
exec-once = google-chat-linux &
exec-once = thunderbird &
exec-once = spotify &
exec-once = $HOME/mitt/ddcgui/result/bin/ddcgui &


bind = CTRL+ALT, S, exec, $terminal -e ssh -Y ice@aio
